FROM snipersim/snipersim@sha256:4f10d4bbfee057e27a52fc0dc33087813feb504bbbfff22902984e356576eaed

RUN chmod -R go+rX /root/sniper/pin_kit

COPY --chmod=755 exercises/3rd/advcomparch-ex3-helpcode/advcomparch_mcpat.py \
    /root/sniper/tools/advcomparch_mcpat.py
